# Generated by Django 3.2.9 on 2022-01-08 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeatures', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30)),
                ('ptype', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=40)),
                ('slug', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
