# Generated by Django 3.2.9 on 2022-01-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeatures', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerambulancemember',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
